### ISSUE TITLE
Type inference in forEach (and probably others)

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_streams#16]
So this code:

```haxe
stream.forEach(function(data) {
  $type(data);
  return Resume;
});
```

gives `Unknown<0>`

Any idea how to make it correctly infer the type?

**Comment by back2dos** [comment]
I just played around a little and I think https://github.com/haxetink/tink_streams/commit/5262af1c6a06c3b09d5817e93a0aeb85a39cc7d7 might improve it quite a bit. Can you confirm?

**Comment by kevinresol** [comment]
This seems worked. I wonder what magic has been done.

**Comment by back2dos** [comment]
It's basically this again: https://github.com/haxetink/tink_core/issues/59

To be able to write `return Resume;`, I had wrapped the function in `{ apply: ... }`, so that the compiler must infer the function bottom up and then uses the implicit cast. But because of that, the argument type becomes unknown.
